### ISSUE TITLE
Screensync can't scan

### ISSUE THREAD

**Issue by pooman10288** [dewgenenny/ScreenSync#3]
Just today I noticed my screensync wont find any bulbs when I click scan.  I hopped on and tried to update to the newest version but I can't seem to get that running.  Did the dist folder go away?  That's how I used to launch it.  

I'm new to python so it very well could be me. Plz help me

**Comment by pooman10288** [comment]
It could be an issue with flux.  When I run a scan in flux it comes back with zero bulbs.

I ran flux_led -s and got back 0 bulbs found

**Comment by pooman10288** [comment]
I get this error when I run screensync.py from the screensync-master folder

 File "C:\Users\*******\Downloads\ScreenSync-master(1)\ScreenSync-master\screensync.py", line 10, in <module>
    from colorthief import ColorThief
ModuleNotFoundError: No module named 'colorthief'

**Comment by pooman10288** [comment]
Duh installed colorthief and got this issue now.

C:\Users\pooma\Downloads\ScreenSync-master(1)\ScreenSync-master>screensync.py
[1280, 720]
['No controllers found :(']
Traceback (most recent call last):
  File "C:\Users\pooma\Downloads\ScreenSync-master(1)\ScreenSync-master\screensync.py", line 201, in connectLED
    bulb = WifiLedBulb(ip)
  File "C:\Users\pooma\AppData\Local\Programs\Python\Python310\lib\site-packages\flux_led\device.py", line 43, in __init__
    self.setup()
  File "C:\Users\pooma\AppData\Local\Programs\Python\Python310\lib\site-packages\flux_led\device.py", line 47, in setup
    self.connect(retry=DEFAULT_RETRIES)
  File "C:\Users\pooma\AppData\Local\Programs\Python\Python310\lib\site-packages\flux_led\sock.py", line 30, in _retry_wrap
    ret = func(self, *args, **kwargs)
  File "C:\Users\pooma\AppData\Local\Programs\Python\Python310\lib\site-packages\flux_led\device.py", line 61, in connect
    self._socket.connect((self.ipaddr, self.port))
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\pooma\Downloads\ScreenSync-master(1)\ScreenSync-master\screensync.py", line 264, in <module>
    bulb = connectLED(str(selectedIP.get()))
  File "C:\Users\pooma\Downloads\ScreenSync-master(1)\ScreenSync-master\screensync.py", line 205, in connectLED
    print("No valid MAC address provided, attempting to use first one discovered: " + scanner.found_bulbs[0]['id'])
NameError: name 'scanner' is not defined

**Comment by pooman10288** [comment]
Well I'm not sure what I did but everything is working as it should again.  I will close the issue.
