### ISSUE TITLE
Variable Scanner not declarated

### ISSUE THREAD

**Issue by fdelfranco** [dewgenenny/ScreenSync#4]
https://github.com/dewgenenny/ScreenSync/blob/134fc21dccd176719047b3b5ece8dae9e8d0bf0a/screensync.py#L205

scanner is not declarated

**Comment by L8Black** [comment]
same

Traceback (most recent call last):
  File "screensync.py", line 201, in connectLED
  File "flux_led\device.py", line 43, in __init__
  File "flux_led\device.py", line 47, in setup
  File "flux_led\sock.py", line 30, in _retry_wrap
  File "flux_led\device.py", line 61, in connect
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "screensync.py", line 264, in <module>
  File "screensync.py", line 205, in connectLED
NameError: name 'scanner' is not defined
